// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PricingService.Infrastructure.Data;

#nullable disable

namespace PricingService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260118184541_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PricingService.Domain.Entities.PricingRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Conditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_percent");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MinNights")
                        .HasColumnType("integer")
                        .HasColumnName("min_nights");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("multiplier");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_name");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_pricing_rules_is_active");

                    b.HasIndex("Priority")
                        .HasDatabaseName("idx_pricing_rules_priority");

                    b.HasIndex("RuleType")
                        .HasDatabaseName("idx_pricing_rules_rule_type");

                    b.ToTable("pricing_rules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245),
                            IsActive = true,
                            Multiplier = 1.5m,
                            Priority = 3,
                            RuleName = "Summer Peak Season",
                            RuleType = "Seasonal",
                            UpdatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245),
                            ValidFrom = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245),
                            IsActive = true,
                            Multiplier = 1.2m,
                            Priority = 2,
                            RuleName = "Weekend Premium",
                            RuleType = "Weekend",
                            UpdatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245),
                            DiscountPercent = 15.0m,
                            IsActive = true,
                            MinNights = 7,
                            Multiplier = 0.85m,
                            Priority = 4,
                            RuleName = "Long Stay Discount",
                            RuleType = "LongStay",
                            UpdatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245)
                        },
                        new
                        {
                            Id = 4L,
                            Conditions = "{\"advanceBookingDays\": 30}",
                            CreatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245),
                            DiscountPercent = 20.0m,
                            IsActive = true,
                            Multiplier = 0.80m,
                            Priority = 5,
                            RuleName = "Early Bird Special",
                            RuleType = "Promotional",
                            UpdatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245),
                            ValidFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PricingService.Domain.Entities.RoomPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("room_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_room_prices_is_active");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("idx_room_prices_room_id");

                    b.HasIndex("RoomType")
                        .HasDatabaseName("idx_room_prices_room_type");

                    b.ToTable("room_prices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BasePrice = 100.00m,
                            CreatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245),
                            Currency = "EUR",
                            IsActive = true,
                            RoomId = 1L,
                            RoomType = "Standard",
                            UpdatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245),
                            ValidFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            BasePrice = 150.00m,
                            CreatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245),
                            Currency = "EUR",
                            IsActive = true,
                            RoomId = 2L,
                            RoomType = "Deluxe",
                            UpdatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245),
                            ValidFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            BasePrice = 250.00m,
                            CreatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245),
                            Currency = "EUR",
                            IsActive = true,
                            RoomId = 3L,
                            RoomType = "Suite",
                            UpdatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245),
                            ValidFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            BasePrice = 500.00m,
                            CreatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245),
                            Currency = "EUR",
                            IsActive = true,
                            RoomId = 4L,
                            RoomType = "Presidential",
                            UpdatedAt = new DateTime(2026, 1, 18, 18, 45, 41, 431, DateTimeKind.Utc).AddTicks(1245),
                            ValidFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
