apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: bookings
type: Opaque
data:
  UserSecrets: <Base64-encoded content of ${APPDATA}/Microsoft/UserSecrets>
  HttpsCerts: <Base64-encoded content of ${APPDATA}/ASP.NET/Https>
