apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seq-ingress
  namespace: bookings
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: seq.bookings.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: seq
            port:
              number: 5341
