apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: bookings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
      - name: seq
        image: datalust/seq:latest
        ports:
        - containerPort: 80
        env:
        - name: ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              name: seq-config
              key: ACCEPT_EULA
        volumeMounts:
        - name: seq-data
          mountPath: /data
      volumes:
      - name: seq-data
        persistentVolumeClaim:
          claimName: seq-data-pvc
