apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seq-data-pvc
  namespace: bookings
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Укажите необходимый объём диска
