<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="9.0.7" />
    <PackageReference Include="Polly" Version="8.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\BookingService.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Bookings.Common" Version="1.0.3" />
  </ItemGroup>
</Project>
