apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
  namespace: bookings
data:
  consul.hcl: |
    data_dir = "/consul/data"

    server = true
    bootstrap_expect = 1
    ui = true

    bind_addr = "0.0.0.0"
    client_addr = "0.0.0.0"

    retry_join = ["127.0.0.1"]

    service {
      name = "Bookings auth service"
      id = "AUTH-SERVICE"
      address = "auth-service.bookings"
      port = 8080
  
      meta {
        prefix = "api/auth"
      }

      check {
        http = "http://auth-service.bookings:8080/health"
        interval = "10s"
        timeout = "5s"
      }
    }
